name: Slow Test PR Workflow

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    paths:
      - trigger-pr-jobs/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Testing"
          sleep 10
          echo "Testing done"

  build-plugin:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - name: Set version
        id: set-version
        run: echo "::set-output name=version::1.2.3.${{ env.GITHUB_RUN_ID }}"

  bump-version-in-composition:
    runs-on: ubuntu-latest
    needs: [ build-plugin ]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: |
          echo embeddable-client-plugin-${{ needs.build-plugin.outputs.version }}.zip >> README.md
          git add README.md
      - name: Commit and create PR
        uses: ./.github/actions/commit-create-pr
        with:
          title: "LKPVW chore: update embeddable client in system composition to ${{ needs.build-plugin.outputs.version }}"
          branch: vmswc/bump-embeddable-client-${{ needs.build-plugin.outputs.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  merge-pull-request:
    name: Merge pull request
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - run: echo "Hello"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Automatically merge pull request
        run: gh pr merge -s
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
