name: Slow Test PR Workflow

on:
  push:
    branches: [main]
    paths:
      - trigger-pr-jobs/**

  pull_request:
    branches: [main]
    paths:
      - trigger-pr-jobs/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Testing"
          sleep 20
          echo "Testing done"

  merge-pull-request:
    name: Merge pull request
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - run: echo "Hello"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Automatically merge pull request
        run: gh pr merge -s
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
